import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

export type LangCode = "en" | "bn" | "hi" | "es" | "fr" | "ar";

export interface Language {
  code: LangCode;
  label: string;
  nativeLabel: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "en", label: "English",  nativeLabel: "English",    flag: "🇺🇸" },
  { code: "bn", label: "Bengali",  nativeLabel: "বাংলা",       flag: "🇧🇩" },
  { code: "hi", label: "Hindi",    nativeLabel: "हिन्दी",       flag: "🇮🇳" },
  { code: "es", label: "Spanish",  nativeLabel: "Español",    flag: "🇪🇸" },
  { code: "fr", label: "French",   nativeLabel: "Français",   flag: "🇫🇷" },
  { code: "ar", label: "Arabic",   nativeLabel: "العربية",    flag: "🇸🇦" },
];

export type Strings = typeof EN;

const EN = {
  // Common
  cancel: "Cancel",
  back: "Back",
  done: "Done",
  tryAgain: "Try Again",
  error: "Error",
  success: "Success",
  save: "Save",
  // Files screen
  allFiles: "All Files",
  recent: "Recent",
  favorites: "Favorites",
  searchFiles: "Search files...",
  noFavorites: "No favorite files",
  noFiles: "No files found",
  // FAB sheet
  createNew: "Create New",
  imagesToPdf: "Images to PDF",
  imagesToPdfSub: "Pick photos from gallery and convert",
  importPdf: "Import PDF",
  importPdfSub: "Open a PDF file from your device",
  mergePdfs: "Merge PDFs",
  mergePdfsSub: "Combine multiple PDFs into one",
  scanDocument: "Scan Document",
  scanDocumentSub: "Use camera to scan a document",
  // Image to PDF
  imageToPdf: "Image to PDF",
  pdfName: "PDF Name",
  pageSize: "Page Size",
  images: "Images",
  addImages: "+ Add Images",
  pickFromGallery: "Pick images from gallery",
  jpgPngSupported: "JPG, PNG supported",
  createPdf: "Create PDF",
  pdfCreated: "PDF Created!",
  createAnother: "Create Another PDF",
  noImagesTitle: "No Images",
  noImagesMsg: "Please add at least one image.",
  pdfErrorMsg: "Failed to create PDF: ",
  pages: "pages",
  // Merge PDF
  mergePdf: "Merge PDF",
  outputFileName: "Output File Name",
  fileName: "File Name",
  pdfFiles: "PDF Files",
  addPdf: "+ Add PDF",
  pickPdfFiles: "Pick PDF files",
  mergeDone: "Merge Complete!",
  mergeAgain: "Merge Again",
  needTwoPdfs: "Need at least 2 PDFs to merge.",
  willMergeIn: "PDFs will be merged in the order shown above.",
  mergePdfBtn: "Merge PDFs",
  pickError: "Failed to pick file.",
  mergeError: "Failed to merge: ",
  // Compress
  pdfCompress: "PDF Compress",
  pickPdf: "Pick PDF",
  tapToPickFile: "Tap to select a file",
  changeFile: "Change File",
  qualityLevel: "Quality Level",
  low: "Low",
  lowSub: "Smaller size",
  medium: "Medium",
  mediumSub: "Balanced",
  high: "High",
  highSub: "Best quality",
  compressBtn: "Compress PDF",
  compressDone: "Compression Complete!",
  compressAnother: "Compress Another File",
  originalSize: "Original Size",
  newSize: "New Size",
  sizeReduced: "% size reduced",
  compressError: "Failed to compress: ",
  // Watermark
  watermark: "Watermark",
  watermarkText: "Watermark Text",
  opacity: "Opacity",
  light: "Light",
  dark: "Dark",
  addWatermarkBtn: "Add Watermark",
  watermarkDone: "Watermark Added!",
  watermarkError: "Failed to add watermark: ",
  // Split PDF
  splitPdf: "Split PDF",
  splitAfterPage: "Split after which page(s)? (comma separated)",
  exampleHint: 'e.g. "3" means pages 1-3 become one file, rest another',
  splitBtn: "Split PDF",
  splitDone: "Split Complete!",
  filesCreated: "files created",
  splitError: "Failed to split: ",
  invalidPages: "Please enter valid page numbers.",
  // Add Text
  addText: "Add Text",
  typeText: "Type your text",
  typeHere: "Type here...",
  pickColor: "Pick Color",
  positionSettings: "Position Settings",
  pageNum: "Page No.",
  xPos: "X Position",
  yPos: "Y Position",
  fontSize: "Font Size",
  addTextBtn: "Add Text to PDF",
  textAdded: "Text Added!",
  textAddError: "Failed to add text: ",
  needPdfAndText: "Please select a PDF and enter text.",
  colorBlack: "Black",
  colorRed: "Red",
  colorBlue: "Blue",
  colorGreen: "Green",
  // Lock PDF
  lockPdf: "Lock PDF",
  enterPassword: "Enter Password",
  password: "Password",
  confirmPassword: "Confirm Password",
  retypePassword: "Re-type password",
  passwordsNoMatch: "Passwords do not match",
  weakPassword: "Weak Password",
  weakPasswordMsg: "Password must be at least 4 characters.",
  passwordsMustMatch: "Both passwords must match.",
  pdfLocked: "PDF Locked!",
  fileSaved: "File saved successfully",
  lockAgain: "Lock Another",
  lockBtn: "Lock PDF",
  lockError: "Failed to lock: ",
  passwordTip: "Keep your password safe. You won't be able to open the PDF if you forget it.",
  // PDF Reader
  pdfReader: "PDF Reader",
  openPdf: "Open PDF",
  pickFromDevice: "Pick a PDF from your device to read",
  pickPdfBtn: "Pick PDF",
  pdfLoaded: "PDF loaded. Use your system viewer to open it on mobile.",
  openAnother: "Open Another PDF",
  // Tools screen
  tools: "Tools",
  convert: "Convert",
  popular: "Popular",
  edit: "Edit",
  requestFeature: "Request a new feature",
  requestFeatureSub: "What other features do you want?",
  activeDotHint: "Colored dot = active tool — tap it!",
  // Settings
  settings: "Settings",
  shareApp: "Share App",
  removeAds: "Remove Ads",
  scanSettings: "Scan Settings",
  securityQuestion: "Security Question",
  language: "Language",
  darkMode: "Dark Mode",
  feedback: "Feedback",
  requestNewFeature: "Request a new feature",
  privacyPolicy: "Privacy Policy",
  version: "Version",
  // Home
  importScanText: "Import images or scan with your camera\nto generate PDFs",
};

const BN: Strings = {
  cancel: "বাতিল",
  back: "ফিরে যান",
  done: "সম্পন্ন",
  tryAgain: "আবার চেষ্টা করুন",
  error: "ত্রুটি",
  success: "সফল",
  save: "সেভ করুন",
  allFiles: "সব ফাইল",
  recent: "সাম্প্রতিক",
  favorites: "প্রিয়",
  searchFiles: "ফাইল খুঁজুন...",
  noFavorites: "কোনো প্রিয় ফাইল নেই",
  noFiles: "কোনো ফাইল পাওয়া যায়নি",
  createNew: "নতুন তৈরি করুন",
  imagesToPdf: "ছবি থেকে PDF",
  imagesToPdfSub: "গ্যালারি থেকে ছবি বেছে PDF বানান",
  importPdf: "PDF আনুন",
  importPdfSub: "ডিভাইস থেকে PDF ফাইল আনুন",
  mergePdfs: "PDF একত্রিত করুন",
  mergePdfsSub: "একাধিক PDF একসাথে যুক্ত করুন",
  scanDocument: "স্ক্যান করুন",
  scanDocumentSub: "ক্যামেরা দিয়ে স্ক্যান করুন",
  imageToPdf: "ছবি থেকে PDF",
  pdfName: "PDF-এর নাম",
  pageSize: "পেজ সাইজ",
  images: "ছবি",
  addImages: "+ ছবি যোগ করুন",
  pickFromGallery: "Gallery থেকে ছবি বেছে নিন",
  jpgPngSupported: "JPG, PNG সাপোর্টেড",
  createPdf: "PDF তৈরি করুন",
  pdfCreated: "PDF তৈরি সম্পন্ন!",
  createAnother: "আরেকটি PDF তৈরি করুন",
  noImagesTitle: "কোনো ছবি নেই",
  noImagesMsg: "অন্তত একটি ছবি বেছে নিন।",
  pdfErrorMsg: "PDF তৈরি করতে সমস্যা হয়েছে: ",
  pages: "পেজ",
  mergePdf: "PDF একত্রিত",
  outputFileName: "আউটপুট ফাইলের নাম",
  fileName: "ফাইলের নাম",
  pdfFiles: "PDF ফাইলসমূহ",
  addPdf: "+ PDF যোগ করুন",
  pickPdfFiles: "PDF ফাইল বেছে নিন",
  mergeDone: "Merge সম্পন্ন!",
  mergeAgain: "আবার করুন",
  needTwoPdfs: "মার্জ করতে কমপক্ষে ২টি PDF দরকার।",
  willMergeIn: "PDF গুলো উপরের ক্রম অনুযায়ী মার্জ হবে।",
  mergePdfBtn: "PDF মার্জ করুন",
  pickError: "ফাইল বেছে নিতে সমস্যা হয়েছে।",
  mergeError: "Merge করতে সমস্যা হয়েছে: ",
  pdfCompress: "PDF সংকুচিত করুন",
  pickPdf: "PDF বেছে নিন",
  tapToPickFile: "ট্যাপ করে ফাইল বেছে নিন",
  changeFile: "ফাইল পরিবর্তন করুন",
  qualityLevel: "কোয়ালিটি লেভেল",
  low: "কম",
  lowSub: "ছোট সাইজ",
  medium: "মাঝারি",
  mediumSub: "সাম্যতা",
  high: "বেশি",
  highSub: "সেরা কোয়ালিটি",
  compressBtn: "Compress করুন",
  compressDone: "Compress সম্পন্ন!",
  compressAnother: "আরেকটি Compress করুন",
  originalSize: "আগের সাইজ",
  newSize: "নতুন সাইজ",
  sizeReduced: "% সাইজ কমেছে",
  compressError: "Compress করতে সমস্যা হয়েছে: ",
  watermark: "ওয়াটারমার্ক",
  watermarkText: "ওয়াটারমার্ক টেক্সট",
  opacity: "স্বচ্ছতা",
  light: "হালকা",
  dark: "গাঢ়",
  addWatermarkBtn: "ওয়াটারমার্ক যোগ করুন",
  watermarkDone: "ওয়াটারমার্ক যোগ হয়েছে!",
  watermarkError: "ওয়াটারমার্ক যোগ করতে সমস্যা হয়েছে: ",
  splitPdf: "PDF ভাগ করুন",
  splitAfterPage: "কোন পেজের পরে ভাগ করবেন? (কমা দিয়ে আলাদা করুন)",
  exampleHint: '"৩" মানে পেজ ১-৩ আলাদা হবে, বাকি পেজ আলাদা',
  splitBtn: "PDF ভাগ করুন",
  splitDone: "Split সম্পন্ন!",
  filesCreated: "টি ফাইল তৈরি হয়েছে",
  splitError: "Split করতে সমস্যা হয়েছে: ",
  invalidPages: "সঠিক পেজ নম্বর দিন।",
  addText: "টেক্সট যোগ করুন",
  typeText: "টেক্সট লিখুন",
  typeHere: "এখানে লিখুন...",
  pickColor: "রঙ বেছে নিন",
  positionSettings: "পজিশন সেটিংস",
  pageNum: "পেজ নং",
  xPos: "X পজিশন",
  yPos: "Y পজিশন",
  fontSize: "ফন্ট সাইজ",
  addTextBtn: "টেক্সট যোগ করুন",
  textAdded: "টেক্সট যোগ হয়েছে!",
  textAddError: "টেক্সট যোগ করতে সমস্যা হয়েছে: ",
  needPdfAndText: "PDF এবং টেক্সট দুটোই দিন।",
  colorBlack: "কালো",
  colorRed: "লাল",
  colorBlue: "নীল",
  colorGreen: "সবুজ",
  lockPdf: "PDF লক করুন",
  enterPassword: "পাসওয়ার্ড দিন",
  password: "পাসওয়ার্ড",
  confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
  retypePassword: "আবার পাসওয়ার্ড দিন",
  passwordsNoMatch: "পাসওয়ার্ড মিলছে না",
  weakPassword: "দুর্বল পাসওয়ার্ড",
  weakPasswordMsg: "কমপক্ষে ৪ অক্ষরের পাসওয়ার্ড দিন।",
  passwordsMustMatch: "দুটো পাসওয়ার্ড একই হতে হবে।",
  pdfLocked: "PDF লক করা হয়েছে!",
  fileSaved: "ফাইল সেভ হয়েছে",
  lockAgain: "আবার লক করুন",
  lockBtn: "PDF লক করুন",
  lockError: "লক করতে সমস্যা হয়েছে: ",
  passwordTip: "পাসওয়ার্ড সুরক্ষিত রাখুন। ভুলে গেলে PDF খোলা যাবে না।",
  pdfReader: "PDF রিডার",
  openPdf: "PDF খুলুন",
  pickFromDevice: "ডিভাইস থেকে PDF বেছে পড়ুন",
  pickPdfBtn: "PDF বেছে নিন",
  pdfLoaded: "PDF লোড হয়েছে। মোবাইলে সিস্টেম ভিউয়ার দিয়ে খুলুন।",
  openAnother: "অন্য PDF খুলুন",
  tools: "টুলস",
  convert: "রূপান্তর",
  popular: "জনপ্রিয়",
  edit: "সম্পাদনা",
  requestFeature: "নতুন ফিচার অনুরোধ করুন",
  requestFeatureSub: "আপনি আর কী ফিচার চান?",
  activeDotHint: "রঙিন ডট মানে টুলটি সক্রিয় — ট্যাপ করুন!",
  settings: "সেটিংস",
  shareApp: "অ্যাপ শেয়ার করুন",
  removeAds: "বিজ্ঞাপন সরান",
  scanSettings: "স্ক্যান সেটিংস",
  securityQuestion: "নিরাপত্তা প্রশ্ন",
  language: "ভাষা",
  darkMode: "ডার্ক মোড",
  feedback: "মতামত",
  requestNewFeature: "নতুন ফিচার অনুরোধ",
  privacyPolicy: "গোপনীয়তা নীতি",
  version: "সংস্করণ",
  importScanText: "ছবি আমদানি করুন বা ক্যামেরা দিয়ে স্ক্যান করুন\nPDF তৈরি করতে",
};

const HI: Strings = {
  cancel: "रद्द करें",
  back: "वापस जाएं",
  done: "हो गया",
  tryAgain: "फिर से प्रयास करें",
  error: "त्रुटि",
  success: "सफल",
  save: "सेव करें",
  allFiles: "सभी फ़ाइलें",
  recent: "हाल की",
  favorites: "पसंदीदा",
  searchFiles: "फ़ाइलें खोजें...",
  noFavorites: "कोई पसंदीदा फ़ाइल नहीं",
  noFiles: "कोई फ़ाइल नहीं मिली",
  createNew: "नया बनाएं",
  imagesToPdf: "Images to PDF",
  imagesToPdfSub: "गैलरी से फ़ोटो चुनें और PDF बनाएं",
  importPdf: "PDF आयात करें",
  importPdfSub: "डिवाइस से PDF फ़ाइल खोलें",
  mergePdfs: "PDF मर्ज करें",
  mergePdfsSub: "कई PDFs को एक में जोड़ें",
  scanDocument: "दस्तावेज़ स्कैन करें",
  scanDocumentSub: "कैमरे से स्कैन करें",
  imageToPdf: "Image to PDF",
  pdfName: "PDF का नाम",
  pageSize: "पेज का आकार",
  images: "चित्र",
  addImages: "+ चित्र जोड़ें",
  pickFromGallery: "गैलरी से चित्र चुनें",
  jpgPngSupported: "JPG, PNG समर्थित",
  createPdf: "PDF बनाएं",
  pdfCreated: "PDF बन गई!",
  createAnother: "एक और PDF बनाएं",
  noImagesTitle: "कोई चित्र नहीं",
  noImagesMsg: "कृपया कम से कम एक चित्र जोड़ें।",
  pdfErrorMsg: "PDF बनाने में समस्या: ",
  pages: "पेज",
  mergePdf: "PDF मर्ज",
  outputFileName: "आउटपुट फ़ाइल नाम",
  fileName: "फ़ाइल नाम",
  pdfFiles: "PDF फ़ाइलें",
  addPdf: "+ PDF जोड़ें",
  pickPdfFiles: "PDF फ़ाइलें चुनें",
  mergeDone: "मर्ज पूर्ण!",
  mergeAgain: "फिर से करें",
  needTwoPdfs: "मर्ज के लिए कम से कम 2 PDF चाहिए।",
  willMergeIn: "PDF ऊपर दिखाए क्रम में मर्ज होंगी।",
  mergePdfBtn: "PDF मर्ज करें",
  pickError: "फ़ाइल चुनने में समस्या।",
  mergeError: "मर्ज करने में समस्या: ",
  pdfCompress: "PDF संपीड़ित करें",
  pickPdf: "PDF चुनें",
  tapToPickFile: "फ़ाइल चुनने के लिए टैप करें",
  changeFile: "फ़ाइल बदलें",
  qualityLevel: "गुणवत्ता स्तर",
  low: "कम",
  lowSub: "छोटा आकार",
  medium: "मध्यम",
  mediumSub: "संतुलित",
  high: "अधिक",
  highSub: "सर्वश्रेष्ठ गुणवत्ता",
  compressBtn: "PDF संपीड़ित करें",
  compressDone: "संपीड़न पूर्ण!",
  compressAnother: "एक और संपीड़ित करें",
  originalSize: "पुराना आकार",
  newSize: "नया आकार",
  sizeReduced: "% आकार कम हुआ",
  compressError: "संपीड़न में समस्या: ",
  watermark: "वॉटरमार्क",
  watermarkText: "वॉटरमार्क टेक्स्ट",
  opacity: "पारदर्शिता",
  light: "हल्का",
  dark: "गहरा",
  addWatermarkBtn: "वॉटरमार्क जोड़ें",
  watermarkDone: "वॉटरमार्क जोड़ा गया!",
  watermarkError: "वॉटरमार्क जोड़ने में समस्या: ",
  splitPdf: "PDF विभाजित करें",
  splitAfterPage: "किस पेज के बाद विभाजित करें? (कॉमा से अलग करें)",
  exampleHint: '"3" का मतलब पेज 1-3 एक फ़ाइल, बाकी दूसरी',
  splitBtn: "PDF विभाजित करें",
  splitDone: "विभाजन पूर्ण!",
  filesCreated: "फ़ाइलें बनाई गईं",
  splitError: "विभाजन में समस्या: ",
  invalidPages: "कृपया सही पेज नंबर दर्ज करें।",
  addText: "टेक्स्ट जोड़ें",
  typeText: "टेक्स्ट टाइप करें",
  typeHere: "यहाँ लिखें...",
  pickColor: "रंग चुनें",
  positionSettings: "स्थिति सेटिंग",
  pageNum: "पेज नं.",
  xPos: "X स्थिति",
  yPos: "Y स्थिति",
  fontSize: "फ़ॉन्ट आकार",
  addTextBtn: "PDF में टेक्स्ट जोड़ें",
  textAdded: "टेक्स्ट जोड़ा गया!",
  textAddError: "टेक्स्ट जोड़ने में समस्या: ",
  needPdfAndText: "कृपया PDF और टेक्स्ट दोनों दें।",
  colorBlack: "काला",
  colorRed: "लाल",
  colorBlue: "नीला",
  colorGreen: "हरा",
  lockPdf: "PDF लॉक करें",
  enterPassword: "पासवर्ड दर्ज करें",
  password: "पासवर्ड",
  confirmPassword: "पासवर्ड की पुष्टि करें",
  retypePassword: "पासवर्ड फिर से दर्ज करें",
  passwordsNoMatch: "पासवर्ड मेल नहीं खाते",
  weakPassword: "कमज़ोर पासवर्ड",
  weakPasswordMsg: "कम से कम 4 अक्षर का पासवर्ड दें।",
  passwordsMustMatch: "दोनों पासवर्ड एक जैसे होने चाहिए।",
  pdfLocked: "PDF लॉक हो गई!",
  fileSaved: "फ़ाइल सेव हो गई",
  lockAgain: "फिर से लॉक करें",
  lockBtn: "PDF लॉक करें",
  lockError: "लॉक करने में समस्या: ",
  passwordTip: "पासवर्ड सुरक्षित रखें। भूलने पर PDF नहीं खुलेगी।",
  pdfReader: "PDF रीडर",
  openPdf: "PDF खोलें",
  pickFromDevice: "डिवाइस से PDF चुनें",
  pickPdfBtn: "PDF चुनें",
  pdfLoaded: "PDF लोड हो गई। मोबाइल पर सिस्टम व्यूअर से खोलें।",
  openAnother: "दूसरी PDF खोलें",
  tools: "टूल्स",
  convert: "Convert",
  popular: "Popular",
  edit: "Edit",
  requestFeature: "नई सुविधा का अनुरोध करें",
  requestFeatureSub: "आप और क्या सुविधाएं चाहते हैं?",
  activeDotHint: "रंगीन डॉट = सक्रिय टूल — टैप करें!",
  settings: "सेटिंग्स",
  shareApp: "ऐप शेयर करें",
  removeAds: "विज्ञापन हटाएं",
  scanSettings: "स्कैन सेटिंग्स",
  securityQuestion: "सुरक्षा प्रश्न",
  language: "भाषा",
  darkMode: "डार्क मोड",
  feedback: "प्रतिक्रिया",
  requestNewFeature: "नई सुविधा का अनुरोध",
  privacyPolicy: "गोपनीयता नीति",
  version: "संस्करण",
  importScanText: "PDF बनाने के लिए चित्र आयात करें\nया कैमरे से स्कैन करें",
};

const ES: Strings = {
  cancel: "Cancelar",
  back: "Volver",
  done: "Listo",
  tryAgain: "Intentar de nuevo",
  error: "Error",
  success: "Éxito",
  save: "Guardar",
  allFiles: "Todos",
  recent: "Recientes",
  favorites: "Favoritos",
  searchFiles: "Buscar archivos...",
  noFavorites: "Sin archivos favoritos",
  noFiles: "No se encontraron archivos",
  createNew: "Crear Nuevo",
  imagesToPdf: "Imágenes a PDF",
  imagesToPdfSub: "Elige fotos de la galería y convierte",
  importPdf: "Importar PDF",
  importPdfSub: "Abrir un archivo PDF desde tu dispositivo",
  mergePdfs: "Combinar PDFs",
  mergePdfsSub: "Combinar varios PDFs en uno",
  scanDocument: "Escanear Documento",
  scanDocumentSub: "Usar cámara para escanear",
  imageToPdf: "Imagen a PDF",
  pdfName: "Nombre del PDF",
  pageSize: "Tamaño de página",
  images: "Imágenes",
  addImages: "+ Añadir Imágenes",
  pickFromGallery: "Elegir imágenes de la galería",
  jpgPngSupported: "JPG, PNG soportados",
  createPdf: "Crear PDF",
  pdfCreated: "¡PDF Creado!",
  createAnother: "Crear Otro PDF",
  noImagesTitle: "Sin Imágenes",
  noImagesMsg: "Por favor añade al menos una imagen.",
  pdfErrorMsg: "Error al crear PDF: ",
  pages: "páginas",
  mergePdf: "Combinar PDF",
  outputFileName: "Nombre del archivo",
  fileName: "Nombre",
  pdfFiles: "Archivos PDF",
  addPdf: "+ Añadir PDF",
  pickPdfFiles: "Elegir archivos PDF",
  mergeDone: "¡Combinación Completa!",
  mergeAgain: "Combinar de nuevo",
  needTwoPdfs: "Se necesitan al menos 2 PDFs para combinar.",
  willMergeIn: "Los PDFs se combinarán en el orden mostrado.",
  mergePdfBtn: "Combinar PDFs",
  pickError: "Error al seleccionar archivo.",
  mergeError: "Error al combinar: ",
  pdfCompress: "Comprimir PDF",
  pickPdf: "Elegir PDF",
  tapToPickFile: "Toca para seleccionar un archivo",
  changeFile: "Cambiar Archivo",
  qualityLevel: "Nivel de Calidad",
  low: "Baja",
  lowSub: "Más pequeño",
  medium: "Media",
  mediumSub: "Equilibrado",
  high: "Alta",
  highSub: "Mejor calidad",
  compressBtn: "Comprimir PDF",
  compressDone: "¡Compresión Completa!",
  compressAnother: "Comprimir Otro Archivo",
  originalSize: "Tamaño Original",
  newSize: "Nuevo Tamaño",
  sizeReduced: "% reducido",
  compressError: "Error al comprimir: ",
  watermark: "Marca de Agua",
  watermarkText: "Texto de Marca de Agua",
  opacity: "Opacidad",
  light: "Claro",
  dark: "Oscuro",
  addWatermarkBtn: "Añadir Marca de Agua",
  watermarkDone: "¡Marca de Agua Añadida!",
  watermarkError: "Error al añadir marca de agua: ",
  splitPdf: "Dividir PDF",
  splitAfterPage: "¿Dividir después de qué página(s)? (separar con coma)",
  exampleHint: '"3" significa páginas 1-3 en un archivo, el resto en otro',
  splitBtn: "Dividir PDF",
  splitDone: "¡División Completa!",
  filesCreated: "archivos creados",
  splitError: "Error al dividir: ",
  invalidPages: "Por favor ingresa números de página válidos.",
  addText: "Añadir Texto",
  typeText: "Escribe tu texto",
  typeHere: "Escribe aquí...",
  pickColor: "Elegir Color",
  positionSettings: "Configuración de Posición",
  pageNum: "Nº de Página",
  xPos: "Posición X",
  yPos: "Posición Y",
  fontSize: "Tamaño de Fuente",
  addTextBtn: "Añadir Texto al PDF",
  textAdded: "¡Texto Añadido!",
  textAddError: "Error al añadir texto: ",
  needPdfAndText: "Por favor selecciona un PDF e ingresa texto.",
  colorBlack: "Negro",
  colorRed: "Rojo",
  colorBlue: "Azul",
  colorGreen: "Verde",
  lockPdf: "Bloquear PDF",
  enterPassword: "Ingresa Contraseña",
  password: "Contraseña",
  confirmPassword: "Confirmar Contraseña",
  retypePassword: "Reescribe la contraseña",
  passwordsNoMatch: "Las contraseñas no coinciden",
  weakPassword: "Contraseña Débil",
  weakPasswordMsg: "La contraseña debe tener al menos 4 caracteres.",
  passwordsMustMatch: "Ambas contraseñas deben coincidir.",
  pdfLocked: "¡PDF Bloqueado!",
  fileSaved: "Archivo guardado",
  lockAgain: "Bloquear Otro",
  lockBtn: "Bloquear PDF",
  lockError: "Error al bloquear: ",
  passwordTip: "Guarda tu contraseña. No podrás abrir el PDF si la olvidas.",
  pdfReader: "Lector PDF",
  openPdf: "Abrir PDF",
  pickFromDevice: "Elige un PDF de tu dispositivo",
  pickPdfBtn: "Elegir PDF",
  pdfLoaded: "PDF cargado. Abre con el visor del sistema en móvil.",
  openAnother: "Abrir Otro PDF",
  tools: "Herramientas",
  convert: "Convertir",
  popular: "Popular",
  edit: "Editar",
  requestFeature: "Solicitar nueva función",
  requestFeatureSub: "¿Qué otras funciones quieres?",
  activeDotHint: "Punto de color = herramienta activa — ¡tócala!",
  settings: "Configuración",
  shareApp: "Compartir App",
  removeAds: "Quitar Anuncios",
  scanSettings: "Config. de Escaneo",
  securityQuestion: "Pregunta de Seguridad",
  language: "Idioma",
  darkMode: "Modo Oscuro",
  feedback: "Comentarios",
  requestNewFeature: "Solicitar nueva función",
  privacyPolicy: "Política de Privacidad",
  version: "Versión",
  importScanText: "Importa imágenes o escanea con tu cámara\npara generar PDFs",
};

const FR: Strings = {
  cancel: "Annuler",
  back: "Retour",
  done: "Terminé",
  tryAgain: "Réessayer",
  error: "Erreur",
  success: "Succès",
  save: "Sauvegarder",
  allFiles: "Tous",
  recent: "Récents",
  favorites: "Favoris",
  searchFiles: "Rechercher des fichiers...",
  noFavorites: "Aucun fichier favori",
  noFiles: "Aucun fichier trouvé",
  createNew: "Créer Nouveau",
  imagesToPdf: "Images en PDF",
  imagesToPdfSub: "Choisissez des photos et convertissez",
  importPdf: "Importer PDF",
  importPdfSub: "Ouvrir un fichier PDF depuis votre appareil",
  mergePdfs: "Fusionner PDFs",
  mergePdfsSub: "Combiner plusieurs PDFs en un seul",
  scanDocument: "Scanner Document",
  scanDocumentSub: "Utiliser l'appareil photo pour scanner",
  imageToPdf: "Image en PDF",
  pdfName: "Nom du PDF",
  pageSize: "Taille de page",
  images: "Images",
  addImages: "+ Ajouter Images",
  pickFromGallery: "Choisir images de la galerie",
  jpgPngSupported: "JPG, PNG supportés",
  createPdf: "Créer PDF",
  pdfCreated: "PDF Créé!",
  createAnother: "Créer un autre PDF",
  noImagesTitle: "Aucune Image",
  noImagesMsg: "Veuillez ajouter au moins une image.",
  pdfErrorMsg: "Erreur lors de la création du PDF: ",
  pages: "pages",
  mergePdf: "Fusionner PDF",
  outputFileName: "Nom du fichier de sortie",
  fileName: "Nom du fichier",
  pdfFiles: "Fichiers PDF",
  addPdf: "+ Ajouter PDF",
  pickPdfFiles: "Choisir fichiers PDF",
  mergeDone: "Fusion Terminée!",
  mergeAgain: "Fusionner de nouveau",
  needTwoPdfs: "Au moins 2 PDFs nécessaires pour fusionner.",
  willMergeIn: "Les PDFs seront fusionnés dans l'ordre affiché.",
  mergePdfBtn: "Fusionner PDFs",
  pickError: "Erreur lors de la sélection du fichier.",
  mergeError: "Erreur lors de la fusion: ",
  pdfCompress: "Compresser PDF",
  pickPdf: "Choisir PDF",
  tapToPickFile: "Appuyer pour sélectionner un fichier",
  changeFile: "Changer Fichier",
  qualityLevel: "Niveau de Qualité",
  low: "Faible",
  lowSub: "Plus petit",
  medium: "Moyen",
  mediumSub: "Équilibré",
  high: "Élevé",
  highSub: "Meilleure qualité",
  compressBtn: "Compresser PDF",
  compressDone: "Compression Terminée!",
  compressAnother: "Compresser un autre",
  originalSize: "Taille Originale",
  newSize: "Nouvelle Taille",
  sizeReduced: "% réduit",
  compressError: "Erreur lors de la compression: ",
  watermark: "Filigrane",
  watermarkText: "Texte du Filigrane",
  opacity: "Opacité",
  light: "Clair",
  dark: "Foncé",
  addWatermarkBtn: "Ajouter Filigrane",
  watermarkDone: "Filigrane Ajouté!",
  watermarkError: "Erreur lors de l'ajout du filigrane: ",
  splitPdf: "Diviser PDF",
  splitAfterPage: "Diviser après quelle(s) page(s)? (séparés par virgule)",
  exampleHint: '"3" signifie pages 1-3 dans un fichier, le reste dans un autre',
  splitBtn: "Diviser PDF",
  splitDone: "Division Terminée!",
  filesCreated: "fichiers créés",
  splitError: "Erreur lors de la division: ",
  invalidPages: "Veuillez entrer des numéros de page valides.",
  addText: "Ajouter Texte",
  typeText: "Tapez votre texte",
  typeHere: "Tapez ici...",
  pickColor: "Choisir Couleur",
  positionSettings: "Paramètres de Position",
  pageNum: "N° de Page",
  xPos: "Position X",
  yPos: "Position Y",
  fontSize: "Taille de Police",
  addTextBtn: "Ajouter Texte au PDF",
  textAdded: "Texte Ajouté!",
  textAddError: "Erreur lors de l'ajout du texte: ",
  needPdfAndText: "Veuillez sélectionner un PDF et entrer du texte.",
  colorBlack: "Noir",
  colorRed: "Rouge",
  colorBlue: "Bleu",
  colorGreen: "Vert",
  lockPdf: "Verrouiller PDF",
  enterPassword: "Entrer Mot de Passe",
  password: "Mot de passe",
  confirmPassword: "Confirmer Mot de Passe",
  retypePassword: "Retaper le mot de passe",
  passwordsNoMatch: "Les mots de passe ne correspondent pas",
  weakPassword: "Mot de passe Faible",
  weakPasswordMsg: "Le mot de passe doit comporter au moins 4 caractères.",
  passwordsMustMatch: "Les deux mots de passe doivent correspondre.",
  pdfLocked: "PDF Verrouillé!",
  fileSaved: "Fichier sauvegardé",
  lockAgain: "Verrouiller un autre",
  lockBtn: "Verrouiller PDF",
  lockError: "Erreur lors du verrouillage: ",
  passwordTip: "Gardez votre mot de passe en sécurité. Vous ne pourrez pas ouvrir le PDF si vous l'oubliez.",
  pdfReader: "Lecteur PDF",
  openPdf: "Ouvrir PDF",
  pickFromDevice: "Choisissez un PDF depuis votre appareil",
  pickPdfBtn: "Choisir PDF",
  pdfLoaded: "PDF chargé. Ouvrez avec la visionneuse système sur mobile.",
  openAnother: "Ouvrir un autre PDF",
  tools: "Outils",
  convert: "Convertir",
  popular: "Populaire",
  edit: "Modifier",
  requestFeature: "Demander une nouvelle fonctionnalité",
  requestFeatureSub: "Quelles autres fonctionnalités voulez-vous?",
  activeDotHint: "Point coloré = outil actif — appuyez dessus!",
  settings: "Paramètres",
  shareApp: "Partager l'App",
  removeAds: "Supprimer les Pubs",
  scanSettings: "Paramètres de Scan",
  securityQuestion: "Question de Sécurité",
  language: "Langue",
  darkMode: "Mode Sombre",
  feedback: "Avis",
  requestNewFeature: "Demander une nouvelle fonctionnalité",
  privacyPolicy: "Politique de Confidentialité",
  version: "Version",
  importScanText: "Importez des images ou scannez avec votre appareil photo\npour générer des PDFs",
};

const AR: Strings = {
  cancel: "إلغاء",
  back: "رجوع",
  done: "تم",
  tryAgain: "حاول مجدداً",
  error: "خطأ",
  success: "نجاح",
  save: "حفظ",
  allFiles: "جميع الملفات",
  recent: "الأخيرة",
  favorites: "المفضلة",
  searchFiles: "البحث عن الملفات...",
  noFavorites: "لا توجد ملفات مفضلة",
  noFiles: "لم يتم العثور على ملفات",
  createNew: "إنشاء جديد",
  imagesToPdf: "صور إلى PDF",
  imagesToPdfSub: "اختر صوراً من المعرض وحوّلها",
  importPdf: "استيراد PDF",
  importPdfSub: "فتح ملف PDF من جهازك",
  mergePdfs: "دمج PDFs",
  mergePdfsSub: "دمج عدة PDFs في واحد",
  scanDocument: "مسح المستند",
  scanDocumentSub: "استخدام الكاميرا للمسح",
  imageToPdf: "صورة إلى PDF",
  pdfName: "اسم PDF",
  pageSize: "حجم الصفحة",
  images: "الصور",
  addImages: "+ إضافة صور",
  pickFromGallery: "اختر صوراً من المعرض",
  jpgPngSupported: "JPG, PNG مدعومة",
  createPdf: "إنشاء PDF",
  pdfCreated: "تم إنشاء PDF!",
  createAnother: "إنشاء PDF آخر",
  noImagesTitle: "لا توجد صور",
  noImagesMsg: "يرجى إضافة صورة واحدة على الأقل.",
  pdfErrorMsg: "فشل في إنشاء PDF: ",
  pages: "صفحات",
  mergePdf: "دمج PDF",
  outputFileName: "اسم ملف الإخراج",
  fileName: "اسم الملف",
  pdfFiles: "ملفات PDF",
  addPdf: "+ إضافة PDF",
  pickPdfFiles: "اختر ملفات PDF",
  mergeDone: "اكتمل الدمج!",
  mergeAgain: "دمج مجدداً",
  needTwoPdfs: "تحتاج إلى PDF واحد على الأقل للدمج.",
  willMergeIn: "سيتم دمج PDFs بالترتيب الموضح أعلاه.",
  mergePdfBtn: "دمج PDFs",
  pickError: "فشل في تحديد الملف.",
  mergeError: "فشل في الدمج: ",
  pdfCompress: "ضغط PDF",
  pickPdf: "اختر PDF",
  tapToPickFile: "اضغط لتحديد ملف",
  changeFile: "تغيير الملف",
  qualityLevel: "مستوى الجودة",
  low: "منخفض",
  lowSub: "أصغر حجم",
  medium: "متوسط",
  mediumSub: "متوازن",
  high: "عالي",
  highSub: "أفضل جودة",
  compressBtn: "ضغط PDF",
  compressDone: "اكتمل الضغط!",
  compressAnother: "ضغط ملف آخر",
  originalSize: "الحجم الأصلي",
  newSize: "الحجم الجديد",
  sizeReduced: "% انخفض الحجم",
  compressError: "فشل في الضغط: ",
  watermark: "علامة مائية",
  watermarkText: "نص العلامة المائية",
  opacity: "الشفافية",
  light: "فاتح",
  dark: "غامق",
  addWatermarkBtn: "إضافة علامة مائية",
  watermarkDone: "تمت إضافة العلامة المائية!",
  watermarkError: "فشل في إضافة العلامة المائية: ",
  splitPdf: "تقسيم PDF",
  splitAfterPage: "التقسيم بعد أي صفحة؟ (مفصولة بفاصلة)",
  exampleHint: '"3" تعني الصفحات 1-3 في ملف، والباقي في آخر',
  splitBtn: "تقسيم PDF",
  splitDone: "اكتمل التقسيم!",
  filesCreated: "ملفات تم إنشاؤها",
  splitError: "فشل في التقسيم: ",
  invalidPages: "يرجى إدخال أرقام صفحات صالحة.",
  addText: "إضافة نص",
  typeText: "اكتب نصك",
  typeHere: "اكتب هنا...",
  pickColor: "اختر لوناً",
  positionSettings: "إعدادات الموضع",
  pageNum: "رقم الصفحة",
  xPos: "الموضع X",
  yPos: "الموضع Y",
  fontSize: "حجم الخط",
  addTextBtn: "إضافة نص إلى PDF",
  textAdded: "تمت إضافة النص!",
  textAddError: "فشل في إضافة النص: ",
  needPdfAndText: "يرجى تحديد PDF وإدخال نص.",
  colorBlack: "أسود",
  colorRed: "أحمر",
  colorBlue: "أزرق",
  colorGreen: "أخضر",
  lockPdf: "قفل PDF",
  enterPassword: "أدخل كلمة المرور",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  retypePassword: "أعد إدخال كلمة المرور",
  passwordsNoMatch: "كلمات المرور غير متطابقة",
  weakPassword: "كلمة مرور ضعيفة",
  weakPasswordMsg: "يجب أن تتكون كلمة المرور من 4 أحرف على الأقل.",
  passwordsMustMatch: "يجب أن تتطابق كلمتا المرور.",
  pdfLocked: "تم قفل PDF!",
  fileSaved: "تم حفظ الملف",
  lockAgain: "قفل آخر",
  lockBtn: "قفل PDF",
  lockError: "فشل في القفل: ",
  passwordTip: "احتفظ بكلمة مرورك بأمان. لن تتمكن من فتح PDF إذا نسيتها.",
  pdfReader: "قارئ PDF",
  openPdf: "فتح PDF",
  pickFromDevice: "اختر PDF من جهازك للقراءة",
  pickPdfBtn: "اختر PDF",
  pdfLoaded: "تم تحميل PDF. افتحه باستخدام عارض النظام على الجوال.",
  openAnother: "فتح PDF آخر",
  tools: "الأدوات",
  convert: "تحويل",
  popular: "الشائع",
  edit: "تعديل",
  requestFeature: "طلب ميزة جديدة",
  requestFeatureSub: "ما الميزات الأخرى التي تريدها؟",
  activeDotHint: "النقطة الملونة = أداة نشطة — انقر عليها!",
  settings: "الإعدادات",
  shareApp: "مشاركة التطبيق",
  removeAds: "إزالة الإعلانات",
  scanSettings: "إعدادات المسح",
  securityQuestion: "سؤال الأمان",
  language: "اللغة",
  darkMode: "الوضع المظلم",
  feedback: "ملاحظات",
  requestNewFeature: "طلب ميزة جديدة",
  privacyPolicy: "سياسة الخصوصية",
  version: "الإصدار",
  importScanText: "استورد صوراً أو امسح بكاميرتك\nلإنشاء PDFs",
};

const TRANSLATIONS: Record<LangCode, Strings> = { en: EN, bn: BN, hi: HI, es: ES, fr: FR, ar: AR };

interface LanguageContextValue {
  lang: LangCode;
  setLang: (code: LangCode) => void;
  t: Strings;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "en",
  setLang: () => {},
  t: EN,
});

const STORAGE_KEY = "@pdf_editor_lang";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("en");

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((stored) => {
      if (stored && stored in TRANSLATIONS) {
        setLangState(stored as LangCode);
      }
    });
  }, []);

  const setLang = (code: LangCode) => {
    setLangState(code);
    AsyncStorage.setItem(STORAGE_KEY, code);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: TRANSLATIONS[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
